<a href="https://colab.research.google.com/github/AndreaBravo52/AlgoritmosClasificacion/blob/main/SVM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Andrea Bravo

A01028579

8 de abril, 2022
# Support Vector Machine


In [ ]:
from google.colab import drive
drive.mount('/content/drive/')

Mounted at /content/drive/


In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

## Solución de tutorial

In [ ]:
bankdata=pd.read_csv('drive/MyDrive/bill_authentication.csv')

In [ ]:
print(bankdata.shape)
bankdata.head()
bankdata.tail(100)

(1372, 5)


Variance  Skewness  Curtosis  Entropy  Class
1272  -4.23330   4.91660  -0.49212 -5.32070      1
1273  -2.36750  -0.43663   1.69200 -0.43018      1
1274  -2.55260  -7.36250   6.92550 -0.66811      1
1275  -3.09860 -10.46020   8.97170 -2.34270      1
1276  -0.89809  -4.48620   2.20090  0.50731      1
...        ...       ...       ...      ...    ...
1367   0.40614   1.34920  -1.45010 -0.55949      1
1368  -1.38870  -4.87730   6.47740  0.34179      1
1369  -3.75030 -13.45860  17.59320 -2.77710      1
1370  -3.56370  -8.38270  12.39300 -1.28230      1
1371  -2.54190  -0.65804   2.68420  1.19520      1

[100 rows x 5 columns]

In [ ]:
X = bankdata.drop('Class', axis=1)
y = bankdata['Class']

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20)

In [ ]:
from sklearn.svm import SVC
svclassifier = SVC(kernel='linear') #usando el kernel lineal
svclassifier.fit(X_train, y_train)

SVC(kernel='linear')

In [ ]:
y_pred = svclassifier.predict(X_test)

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[149   0]
 [  0 126]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       149
           1       1.00      1.00      1.00       126

    accuracy                           1.00       275
   macro avg       1.00      1.00      1.00       275
weighted avg       1.00      1.00      1.00       275



### Predicciones

In [ ]:
print(svclassifier.predict([[3.62160, 8.6661, -2.8073,-0.44699]]))
print(svclassifier.predict([[1.10500, 7.4432,0.41099,-3.03320]]))
print(svclassifier.predict([[-4.23330,4.91660,-0.49212,-5.32070]]))
print(svclassifier.predict([[0.964410,5.83950,2.32350,0.066365]]))
print(svclassifier.predict([[-2.227900,4.095100,-4.803700,-2.111200]]))

[0]
[0]
[1]
[0]
[1]


/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  "X does not have valid feature names, but"
/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  "X does not have valid feature names, but"
/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  "X does not have valid feature names, but"
/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  "X does not have valid feature names, but"
/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  "X does not have valid feature names, but"


## Solución con base de datos Iris

In [ ]:
iris=pd.read_csv('drive/MyDrive/iris.csv')

In [ ]:
print(iris.shape)
iris.head()

(150, 5)


Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [ ]:
X=iris.drop('Species', axis=1)
y=iris['Species']

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20)


In [ ]:
svclassifierL = SVC(kernel='linear') #usando el kernel lineal
svclassifierL.fit(X_train, y_train)
y_predL = svclassifierL.predict(X_test)
svclassifierP = SVC(kernel='poly',degree=8) #usando el kernel lineal
svclassifierP.fit(X_train, y_train)
y_predP = svclassifierP.predict(X_test)
svclassifierG= SVC(kernel='rbf') #usando el kernel lineal
svclassifierG.fit(X_train, y_train)
y_predG = svclassifierG.predict(X_test)

In [ ]:
from sklearn import metrics

In [ ]:
print('Evaluación kernel lineal')
print(confusion_matrix(y_test,y_predL))
print(classification_report(y_test,y_predL))
print("Accuracy:",metrics.accuracy_score(y_test, y_predL))
print('Evaluación kernel polinomial')
print(confusion_matrix(y_test,y_predP))
print(classification_report(y_test,y_predP))
print("Accuracy:",metrics.accuracy_score(y_test, y_predP))
print('Evaluación kernel gaussiano')
print(confusion_matrix(y_test,y_predG))
print(classification_report(y_test,y_predG))
print("Accuracy:",metrics.accuracy_score(y_test, y_predG))

Evaluación kernel lineal
[[16  0  0]
 [ 0  3  0]
 [ 0  0 11]]
              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        16
  versicolor       1.00      1.00      1.00         3
   virginica       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

Accuracy: 1.0
Evaluación kernel polinomial
[[16  0  0]
 [ 0  3  0]
 [ 0  2  9]]
              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        16
  versicolor       0.60      1.00      0.75         3
   virginica       1.00      0.82      0.90        11

    accuracy                           0.93        30
   macro avg       0.87      0.94      0.88        30
weighted avg       0.96      0.93      0.94        30

Accuracy: 0.9333333333333333
Evaluación kernel gaussiano
[[16  0  0]
 [ 0  3  0]
 [ 0  1 10]]
  

### Predicciones

In [ ]:
print(svclassifierL.predict([[5.0, 3.6, 1.4, 0.2]])) #prediccion con kernel lineal
print(svclassifierL.predict([[6.7, 3.0, 5.2, 2.3]])) #prediccion con kernel lineal
print(svclassifierP.predict([[5.9, 3.0, 5.1, 1.8]])) #prediccion con kernel polinomial
print(svclassifierP.predict([[5.1, 3.5, 1.4, 0.2]])) #prediccion con kernel polinomial
print(svclassifierG.predict([[5.7,	2.6, 3.5,	1.0	]])) #prediccion con kernel gaussiano

['setosa']
['virginica']
['virginica']
['setosa']
['versicolor']


/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  "X does not have valid feature names, but"
/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  "X does not have valid feature names, but"
/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  "X does not have valid feature names, but"
/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  "X does not have valid feature names, but"
/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  "X does not have valid feature names, but"
